### PR TITLE
Pages displaying Page not Found message in browser tab

### PR DESCRIPTION
**Pull request by roborourke**
The browser tab shows a "Page not Found" message even though all of the pages are being found.

### CODE REVIEW

**Comment by johnbillion** [comment]
Chatted with Rob about this, this is a hacky fix for now.

**Comment by petyaraykovska** [comment]
Just adding a quick comment - the Page not found title appears on all posts as well as pages.

**Comment by roborourke** [comment]
Done but we still send 404 headers for these URLs so opengraph crawlers ignore it.

**Comment by joehoyle** [comment]
I added real rewrites for thse urls now

**Pull request merged**
